### ISSUE TITLE
Allow setting certificate-authority-data with service account approach of configuration

### ISSUE THREAD

**Issue by underyx** [Azure/k8s-set-context#2]

**Comment by shashankbarsin** [comment]
We've added this capability in #3. This was supposed to be have been supported in this action from the get go, but there was an error in code and documentation. The k8s-secret input is expected to contain the contents of the secret associated with the service account of concern. This is then used to parse both the token and the cert...

For fetching Secret object required to connect and authenticate with the cluster, the following sequence of commands need to be run:

```
kubectl get serviceAccounts <service-account-name> -n <namespace> -o 'jsonpath={.secrets[*].name}'
```
```
kubectl get secret <service-account-secret-name> -n <namespace> -o json
```

The contents from the output of above command can be added as secret to the repository and later used in this action as shown below:

```yaml
- uses: azure/k8s-set-context@v1
  with:
    method: service-account
    k8s-url: <URL of the clsuter's API server>
    k8s-secret: <secret associated with the service account>
  id: setcontext
```
