### ISSUE TITLE
Error: Input required and not supplied: kubeconfig (bump v2)

### ISSUE THREAD

**Issue by mac2000** [Azure/k8s-set-context#42]
After dependabot tried to upgrade dependency from v1 to v2 workflows brake with error: "Error: Input required and not supplied: kubeconfig"

![image](https://user-images.githubusercontent.com/88868/148760327-124b0083-36e7-476f-a959-5464e02dce20.png)

![image](https://user-images.githubusercontent.com/88868/148760367-94e128e9-d3d1-4a23-b653-f03bc6e202eb.png)

**Comment by OliverMKing** [comment]
Hi! When you set the method to kubeconfig you must include the kubeconfig. From the screenshot it looks like it's not being supplied.

**Comment by OliverMKing** [comment]
Going to close this for now. Please reopen if you're still having problems.

**Comment by chinochao** [comment]
@OliverMKing It seems that @mac2000  is passing the secret to the kubeconfig. 

@mac2000 It might be a bug but I was able to get it working this way.

```
      - uses: azure/k8s-set-context@v3
        with:
          kubeconfig: $KUBECONFIG_SECRET
        env:
          KUBECONFIG_SECRET: ${{ secrets.KUBECONFIG }}
```

Passing the secret directly does not work.
