### ISSUE TITLE
service-account usage with k8s-create-secret

### ISSUE THREAD

**Issue by laat** [Azure/k8s-set-context#48]
When I use k8s-url and k8s-secret:

```yaml
- uses: azure/k8s-set-context@v2
  with:
    method: service-account
    k8s-url: <URL of the cluster's API server>
    k8s-secret: <secret associated with the service account>
```

with azure/k8s-create-secret:
```yaml
- name: Set secret
  uses: azure/k8s-create-secret@v2
  with:
    namespace: 'myapp'
    secret-type: 'generic'
    secret-name: 'myapp-secret'
    string-data: ${{ secrets.SECRET_STRING_DATA }}
  id: create-secret
```

I get an error in the create secret step: `Error: clusters[0].name is missing`

https://github.com/kubernetes-client/javascript/blob/6626ff029d5369680a5497d31c8f3094d7af26d8/src/config_types.ts#L45-L49

I assume it's because we do not set a name here:
https://github.com/Azure/k8s-set-context/blob/6c102e2f8d9583d36b4b231bf4d54c1243e0a9b3/src/kubeconfigs/default.ts#L65-L70
