### ISSUE TITLE
How to set multiple contexts?

### ISSUE THREAD

**Issue by woutersf** [Azure/k8s-set-context#60]
I'm sorry if this is not the right place for this. 
Thanks for your tool , we rely on it at our client. 🙏

I'm not sure if it's possible or not with this github action. And not sure where to ask? 
I'm moving a file from one cluster to another (let's say tst to acc for example). 

One of my first steps is

```
  move-file:
    environment: 
      name: tst
    steps:
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
        id: setcontext
```

After this I can display the contexts like so:
`kubectl config get-contexts`
It shows me the 1 cluster:

```
CURRENT   NAME      CLUSTER            AUTHINFO   NAMESPACE
*         context   example-tst   user       examplenamespace-tst

```

When I issue the setcontext again, nothing changes (I think because the environment is declared on a higher level (environment)?

So I'm not sure on how in a step to 
- change the context?
- set 2 clusters as contexts from the start (but how then)?
(and what would the best option be? 

Where should I look to find answers to this?

**Comment by woutersf** [comment]
If I in a second step use 
```
      # Switch to cluster  
      - uses: azure/aks-set-context@v3
        with:
           resource-group: 'rg-example'
           cluster-name: 'example-cluster-name'
```
I get 
`Message: The client 'UUIDUUIDUUID' with object id 'UUIDUUIDUUID' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/listClusterUserCredential/action' over scope '/subscriptions/UUIDUUIDUUID/resourceGroups/rg-example/providers/Microsoft.ContainerService/managedClusters/examplecluster-admin' or the scope is invalid. If access was recently granted, please refresh your credentials.`

Should I refresh the credentials first in a separate github action?
